version: '3.8'

services:
  web:
    container_name: -server
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - app:/app
    networks:
      - network
    env_file:
      - .env

volumes:
  dbdata:
  app:

networks:
  network:
    driver: bridge